.TH GREETING 1 "Dec 2025" "1.0" "Greeting Manual"
.SH NAME
greeting \- print a friendly greeting
.SH SYNOPSIS
.B greeting
[\fINAME\fR]
.SH DESCRIPTION
.B greeting
prints a greeting message to standard output. If \fINAME\fR is provided, it greets that name; otherwise, it greets the World.
.SH OPTIONS
.TP
.BR \-\-help
Display help message and exit.
